apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: sealights-go-demo
 name: sealights-go-demo
 namespace: flavius-test
spec:
 replicas: 1
 selector:
   matchLabels:
     app: sealights-go-demo
 template:
   metadata:
     labels:
       app: sealights-go-demo
   spec:
     containers:
       - image: quay.io/flacatus/konflux-sealights:0.1
         imagePullPolicy: Always
         name: sealights-go-demo
         ports:
           - containerPort: 8080