apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sealights-instrumentation
spec:
  description: |
    An integration test which provisions an ephemeral Hypershift cluster.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - description: "Image used to build sealights instrumentation"
      name: output-image
      default: 'quay.io/redhat-user-workloads/konflux-qe-team-tenant/go-calc-demo:sealights'
      type: string
  tasks:
    - name: test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/flacatus/tekton-integration-catalog.git
          - name: revision
            value: sealights_build
          - name: pathInRepo
            value: common/tasks/test-metadata/0.1/test-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: test-name
          value: $(context.pipelineRun.name)
    - name: clone-repository
      params:
        - name: enableSymlinkCheck
          value: "false"
        - name: url
          value: $(tasks.test-metadata.results.source-repo-url)
        - name: revision
          value: $(tasks.test-metadata.results.git-revision)
        - name: ociStorage
          value: $(params.output-image)-$(tasks.test-metadata.results.git-revision).git
      runAfter:
        - test-metadata
      taskRef:
        params:
          - name: name
            value: git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:4bf48d038ff12d25bdeb5ab3e98dc2271818056f454c83d7393ebbd413028147
          - name: kind
            value: task
        resolver: bundles
    - name: sealights-instrumentation
      runAfter:
        - clone-repository
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/flacatus/tekton-integration-catalog.git
          - name: revision
            value: sealights_build
          - name: pathInRepo
            value: tasks/sealights/sealights-go/0.1/sealights-go.yaml
      params:
        - name: source-artifact
          value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
        - name: go-version
          value: "1.22"
        - name: sealights-secret
          value: "sealights-credentials"
        - name: component
          value: $(tasks.test-metadata.results.component-name)
        - name: branch
          value: $(tasks.test-metadata.results.source-repo-branch)
        - name: revision
          value: $(tasks.test-metadata.results.git-revision)
        - name: oci-storage
          value: $(params.output-image)-$(tasks.test-metadata.results.git-revision).git
    - name: build-sealights
      runAfter:
        - sealights-instrumentation
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/flacatus/tekton-integration-catalog.git
          - name: revision
            value: sealights_build
          - name: pathInRepo
            value: tasks/sealights/build-sealights-container/0.1/build-sealights-container.yaml
      params:
        - name: source-artifact
          value: $(tasks.sealights-instrumentation.results.source-artifact)
        - name: revision
          value: $(tasks.test-metadata.results.git-revision)
        - name: image
          value: "$(params.output-image)-$(tasks.test-metadata.results.git-revision)-sealights"
